# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: sabyasachi
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  I am Sabyasachi, a data science undergrad.
baseurl: "/thoughts" # the subpath of your site, e.g. /blog
url: "https://watham15.github.io/thoughts" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  watham15

# Build settings
# theme: no-style-please
remote_theme: riggraz/no-style-please
plugins:
- jekyll-feed
- jekyll-remote-theme # add this line to the plugins list if you already have one

theme_config:
  # appearance: "auto"
  show_description: true
  lowercase_titles: true
  back_home_text: "↩"
  date_format: "%d-%m-%Y"
